version: '3.1'
services:
    postgresdb:
        image: postgres
        container_name: postgres-db-go-management-service-example
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        healthcheck:
            test: pg_isready -U postgres -d postgres
            interval: 10s
            timeout: 3s
            retries: 5

    migration:
        build:
            context: ../db_migration/
            dockerfile: ../db_migration/Dockerfile
        environment:
            DB_PASSWORD: ${DB_PASSWORD}
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - postgresdb
        depends_on:
            - postgresdb